### ISSUE TITLE
Initial release reported as damaged on Big Sur

### ISSUE THREAD

**Issue by ronenrozner** [PortableApps/MacHelper#1]
First time launch of Mac helper (Ver 1.0) is reported as damaged by macOS and can't be opened. 
Copied the app from the dmg file to ~/Documents. control+click then Open.

macOS Big Sur 11.7.5
Intel core i5.

**Comment by JohnTHaller** [comment]
I've added instructions to the release page:

On newer versions of macOS, Apple has set it so that unsigned downloaded apps can't be used and will show an error saying they are damaged or corrupt. To allow the app, after copying the PortableAppsMacHelper to your Documents folder, open a terminal window and run the following command:

sudo xattr -d com.apple.quarantine ~/Documents/PortableAppsMacHelper.app

This removes the app from the macOS quarantine and allows it to work as normal. We're applying for the Apple Developer program now and will be signing once we have the funds for the $100 per year fee and Apple approves the Rare Ideas, LLC program membership.
